version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  fpm:
    image: php:8-fpm
    volumes:
      - ./app:/var/www/html
